version: '2'

networks:
  front:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      front:
        ipv4_address: 172.19.0.10

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    ports:
      - "9093:9093"
    networks:
      front:
        ipv4_address: 172.19.0.11

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      front:
        ipv4_address: 172.19.0.12

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      front:
        ipv4_address: 172.19.0.13

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8899:8080"
    networks:
      front:
        ipv4_address: 172.19.0.14

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    hostname: mysql-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "root:mysql2020@(172.18.0.8:3306)/"
    ports:
      - "9104:9104"
    networks:
      front:
        ipv4_address: 172.19.0.15