spring:
  datasource:
    url: jdbc:p6spy:mysql://116.85.4.107/boot_03?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: boot
    password: boot123
